### ISSUE TITLE
Export torchscript

### ISSUE THREAD

**Issue by ducanhcao-tech** [WildChlamydia/MiVOLO#25]
I added a few lines of code to the file "mivolo\model\mi_volo.py" as follows:
if __name__ == "__main__":
     model = MiVOLO("D:\Project\MiVOLO-main\models\mivolo_imbd.pth.tar", half=True, device="cpu")
     example = torch.rand(1,3,224,224)
     ms = torch.jit.trace(model, example)

Just to test the ability to convert to torchscript but I'm getting an error with the following message:
(mivolo) D:\Project\MiVOLO-main>python mivolo/model/mi_volo.py
Traceback (most recent call last):
   File "D:\Project\MiVOLO-main\mivolo\model\mi_volo.py", line 243, print <module>
     ms = torch.jit.trace(model, example)
   File "C:\Users\mrcao\miniconda3\envs\mivolo\lib\site-packages\torch\jit\_trace.py", line 853, print trace
     name = _qualified_name(func)
   File "C:\Users\mrcao\miniconda3\envs\mivolo\lib\site-packages\torch\_jit_internal.py", line 1152, in _qualified_name
     raise RuntimeError("Could not get name of python class object")
RuntimeError: Could not get name of python class object

The reason I need the torchscript file is to be able to inference on C++.
Thanks for your solution. I'm a newbie and so need your help.

**Comment by ducanhcao-tech** [comment]
After looking at the problem more carefully, I found a solution.
There are 2 errors in my code: First, the model needs to be inherited from nn.Module. Second, input shape is (1, 6, 224, 224).
The following code in the mi_volo.py file worked:

if __name__ == "__main__":
     model = MiVOLO("mivolo_imbd.pth.tar", half=True, device="cpu").model
     example = torch.rand(1,6,224,224)
     model_torch_script = torch.jit.trace(model, example)
     model_torch_script.save("mivolo_imbd_torchscript.pt")

**Comment by ducanhcao-tech** [comment]
Example for cuda export
```
if __name__ == "__main__":
    model = MiVOLO("models/mivolo_agegender_faceonly_422.pth.tar", half=False, device="cuda:0").model
    example = torch.rand(1,3,224,224)
    example = example.to("cuda:0")
    model_torch_script = torch.jit.trace(model, example)
    model_torch_script.save("mivolo_agegender_faceonly_422.torchscript")
```
